### ISSUE TITLE
More usage examples in ReadMe

### ISSUE THREAD

**Issue by CCninja86** [its-rigs/Trolly#44]
Hi,

Could you please update the ReadMe with more usage examples for functions, specifically ones such as add_card(). I can't figure out how to create a new card on a list.

**Comment by plish** [comment]
Sure I'll try and flesh it out soon. In the mean time you can add a card like this:

list.add_card({'name': 'my new card'})

You can find the arguments that Trello accepts for this operation here https://developers.trello.com/advanced-reference/list#post-1-lists-idlist-cards

Hope that helps in the mean time.

**Comment by ingsoctexas** [comment]
Could you please share a snippet of code showing how to delete a card?

**Comment by its-rigs** [comment]
@ingsoctexas you would have to retrieve the card and then use close_card() method on that object. Hope that helps.

**Comment by ingsoctexas** [comment]
Certainly does- thank you!
